In [1]:
import numpy as np

In [2]:
rolls=np.random.randint(1,7,size=10)
rolls

array([3, 3, 2, 6, 5, 5, 4, 5, 1, 6], dtype=int32)

In [3]:
rolls+10

array([13, 13, 12, 16, 15, 15, 14, 15, 11, 16], dtype=int32)

In [4]:
rolls*2

array([ 6,  6,  4, 12, 10, 10,  8, 10,  2, 12], dtype=int32)

In [5]:
rolls<=3

array([ True,  True,  True, False, False, False, False, False,  True,
       False])

In [6]:
xlist=[[1,2],[3,4]]
x=np.asarray(xlist)
print(type(xlist))
x

<class 'list'>


array([[1, 2],
       [3, 4]])

In [7]:
x[1,-1]

np.int64(4)

In [8]:
xlist[1,-1]

TypeError: list indices must be integers or slices, not tuple

In [14]:
nums = [4,2,-5,-1,6,-3]
nums=sorted(nums,key=lambda x: x**2)
nums

[-1, 2, -3, 4, -5, 6]

Help on package sklearn:

NAME
    sklearn - Configure global settings and get information about the working environment.

PACKAGE CONTENTS
    __check_build (package)
    _build_utils (package)
    _config
    _cyutility
    _distributor_init
    _isotonic
    _loss (package)
    _min_dependencies
    base
    calibration
    cluster (package)
    compose (package)
    conftest
    covariance (package)
    cross_decomposition (package)
    datasets (package)
    decomposition (package)
    discriminant_analysis
    dummy
    ensemble (package)
    exceptions
    experimental (package)
    externals (package)
    feature_extraction (package)
    feature_selection (package)
    frozen (package)
    gaussian_process (package)
    impute (package)
    inspection (package)
    isotonic
    kernel_approximation
    kernel_ridge
    linear_model (package)
    manifold (package)
    metrics (package)
    mixture (package)
    model_selection (package)
    multiclass
    multioutput
    naive_