In [1]:
import numpy as np

In [2]:
rolls=np.random.randint(1,7,size=10)
rolls

array([5, 6, 6, 6, 6, 6, 2, 1, 4, 2], dtype=int32)

In [3]:
rolls+10

array([15, 16, 16, 16, 16, 16, 12, 11, 14, 12], dtype=int32)

In [4]:
rolls*2

array([10, 12, 12, 12, 12, 12,  4,  2,  8,  4], dtype=int32)

In [5]:
rolls<=3

array([False, False, False, False, False, False,  True,  True, False,
        True])

In [6]:
xlist=[[1,2],[3,4]]
x=np.asarray(xlist)
print(type(xlist))
x

<class 'list'>


array([[1, 2],
       [3, 4]])

In [7]:
x[1,-1]

np.int64(4)

In [ ]:
nums = [4,2,-5,-1,6,-3]
nums=sorted(nums,key=lambda x: x**2)
nums

[-1, 2, -3, 4, -5, 6]

In [26]:
import torch
torch.manual_seed(0)
x=torch.randn(size=(2,4))
print(x)

tensor([[ 1.5410, -0.2934, -2.1788,  0.5684],
        [-1.0845, -1.3986,  0.4033,  0.8380]])
